### ISSUE TITLE
Unable to start worker following README

### ISSUE THREAD

**Issue by r0zar** [AnilRedshift/yatlab-worker#7]
Hey, first thanks for this library, I'm learning Elixir as I go so it's a big help.

I'm following the instructions in the readme, and have run into a few issues.

First, I was unable to get the `mix release` to finish without error, and ended up bumping the version of distillery to 2.0 which _seemed_ to fix the problem.

I'm now able to get a release but when I run `_build/dev/rel/worker/bin/worker console`

I see the following:

```
➜  yatlab-worker git:(master) ✗ _build/dev/rel/worker/bin/worker console   
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(worker@127.0.0.1)1> 
14:14:16.767 [error] GenServer #PID<0.1522.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, %{code: "db_error", message: nil}}. This protocol is implemented for: Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.into/4
    (worker) lib/team_monitor.ex:48: TeamMonitor.update/1
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :update
State: #MapSet<[]>

14:14:16.870 [error] GenServer #PID<0.1530.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, %{code: "db_error", message: nil}}. This protocol is implemented for: Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.into/4
    (worker) lib/team_monitor.ex:48: TeamMonitor.update/1
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :update
State: #MapSet<[]>

14:14:16.971 [error] GenServer #PID<0.1531.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, %{code: "db_error", message: nil}}. This protocol is implemented for: Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.into/4
    (worker) lib/team_monitor.ex:48: TeamMonitor.update/1
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :update
State: #MapSet<[]>

14:14:17.074 [error] GenServer #PID<0.1532.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:error, %{code: "db_error", message: nil}}. This protocol is implemented for: Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20190202-21222-1ilp2g0/elixir-1.8.1/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.into/4
    (worker) lib/team_monitor.ex:48: TeamMonitor.update/1
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :update
State: #MapSet<[]>

14:14:17.075 [info]  Application worker exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,worker,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,worker,shutdown})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by r0zar** [comment]
From the error, It looks like an issue with the DB (postgres) connection.

I have some basic defaults in my connection info, so not sure what's up.

DB_HOST: localhost
DB_PATH: postgres
DB_USER: myLogin
DB_PASS: myPass

**Comment by r0zar** [comment]
I did a default installation of postgres, could you give an example of connection info for a localhost connection?

**Comment by r0zar** [comment]
I'm able to connect directly with the creds:
<img width="975" alt="Screen Shot 2019-04-12 at 2 35 06 PM" src="https://user-images.githubusercontent.com/4655474/56061940-7ee10400-5d30-11e9-91d0-b52da5f7c6c1.png">

**Comment by intentionally-left-nil** [comment]
Hi, thanks for the report. I haven't touched this code in close to a year, so I've lost a lot of context on how it works. I can confirm, (surprisingly!!) that the built-in docker file crashes on startup.

I don't have time at the moment to take a look, but might be able to get to this in a few days. Until then, you might find better luck untangling distillery from the dependencies and changing config.exs to directly query the OS variables.

e.g. db_host: System.get_env("DB_HOST"),
  db_user: "${DB_USER}",
  db_password: "${DB_PASS}",
  db_path: "${DB_PATH}",

...etc.

**Comment by r0zar** [comment]
Thanks for the quick reply!
I've narrowed the problem down to when I call `get_teams()` in the `team_monitor.ex`, the error will be thrown. 

I suspect it's trying to query the database, and I haven't created any kind of schema, nor obviously added any data. What was your solution for this, I can make a PR when I complete it if necessary.

**Comment by r0zar** [comment]
Okay, I see your doing that via the web with Yatlab. gotcha!

**Comment by r0zar** [comment]
Okay, I was able to start it once I used Yatlab to migrate the database. So the only actual issue i ran into was the distillery version one. You can close this if you don't care to make any changes. Thanks.
